### PR TITLE
Update java docs for new API change

### PR DESCRIPTION
**Pull request by cogmission**
@brev @rhyolight - Was able to submit PR but it won't merge all these html files. Magic needed? :)

### CODE REVIEW

**Comment by rhyolight** [comment]
@cogmission I don't think you started from the tip of the `gh-pages` branch. Standby...

**Comment by rhyolight** [comment]
@cogmission Merge https://github.com/cogmission/numenta.org/pull/2 to get up to date.

**Comment by cogmission** [comment]
Ok merged. What did you do? That was cool!

**Comment by rhyolight** [comment]
@cogmission I just created a branch off your `java-update-synchronous-api` branch, then I did a `git pull upstream gh-pages` to get the most recent changes (and a TON of merge conflicts). And because you want to overwrite all those docs with local changes, I ran `git checkout --ours docs` to accept all your changes for merge conflicts and pushed to my remote, then opened a PR against your `java-update-synchronous-api` branch. :)

**Comment by cogmission** [comment]
@rhyolight Sweet! I have to remember that! (the "--ours" thingy especially)

**Pull request merged**
