### PR TITLE
Added Pingdom RUM script to head of all pages.

### PR DESCRIPTION
**Pull request by rhyolight**
@brev please review

### CODE REVIEW

**Comment by rhyolight** [comment]
https://www.pingdom.com/product/performance-monitoring

**Comment by brev** [comment]
:+1: I'll investigate for numenta.com thanks

**Comment by brev** [comment]
LGTM

**Comment by rhyolight** [comment]
I can't add another "realtime user monitoring" check without upgrading my pingdom account, which I'm not planning on doing, so I wouldn't worry about Numenta.com. I'm not sure this service will give us anything useful, but I'll let you know once it runs for awhile.

**Pull request merged**
