### PR TITLE
Third time is a charm? Lock down changes to `docs/htm.java` dir. 

### PR DESCRIPTION
**Pull request by brev**
Third time is a charm? Lock down changes to `docs/htm.java` dir. 
Verified all changes are here. See PRs #219 #220. cc @cogmission

### CODE REVIEW

**Comment by cogmission** [comment]
Awesome work Brev! :-)

**Comment by brev** [comment]
thanks :) should be live now.

**Comment by cogmission** [comment]
Verified!

On Mon, Jul 27, 2015 at 1:42 PM, Brev Patterson <notifications@github.com>
wrote:

> thanks :) should be live now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/numenta.org/pull/221#issuecomment-125301617>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by cogmission** [comment]
@Brev

Added not to htm.java's Change log :
https://github.com/numenta/htm.java/blob/master/CHANGELOG.md

On Mon, Jul 27, 2015 at 1:44 PM, cogmission (David Ray) <
cognitionmission@gmail.com> wrote:

> Verified!
>
> On Mon, Jul 27, 2015 at 1:42 PM, Brev Patterson <notifications@github.com>
> wrote:
>
>> thanks :) should be live now.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/numenta/numenta.org/pull/221#issuecomment-125301617>.
>>
>
>
>
> --
> *With kind regards,*
>
> David Ray
> Java Solutions Architect
>
> *Cortical.io <http://cortical.io/>*
> Sponsor of:  HTM.java <https://github.com/numenta/htm.java>
>
> d.ray@cortical.io
> http://cortical.io
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Pull request merged**
