### PR TITLE
Trying to merge in Docs changes to a current version of the site.

### PR DESCRIPTION
**Pull request by brev**
Trying to merge in @cogmission's docs changes to a current version of the site.
Looks like changes on PR # 219 were to an older version of the site?
(I think! I'm not the best at git yet). :)
This should be all the changes to `docs/` from
`cogmission:htm-java-update-0.5.2` branch, going into a current version of repo.

Please make sure this looks OK @cogmission @rhyolight thanks!

### CODE REVIEW

**Comment by brev** [comment]
This is another attempt at closed PR #219 which had some merge problems it seemed.

**Comment by cogmission** [comment]
Thank you so much @brev for struggling through this! :+1: 

It looks fine, as long as the entire directory was copied over, it should be fine...

I appreciate it!

**Comment by cogmission** [comment]
Oh btw, I tried to update my repo before doing my PR, just so you know - it said my repo was "up to date".

But I agree, the cause you sited would explain the behavior we're getting...

**Comment by rhyolight** [comment]
Thanks for working this out, @brev. And @cogmission...

you're fired

**Comment by brev** [comment]
@cogmission working on verifying the entire dir just to be safe

**Comment by cogmission** [comment]
@brev Sounds good! I appreciate it...

@rhyolight :-P

On Mon, Jul 27, 2015 at 1:17 PM, Brev Patterson <notifications@github.com>
wrote:

> @cogmission <https://github.com/cogmission> working on verifying the
> entire dir just to be safe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/numenta.org/pull/220#issuecomment-125293894>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by brev** [comment]
VOID. See #221

**Pull request closed without merging**
