### PR TITLE
Hierarchal to hierarchical

### LINKED ISSUE #178: Fix misspellings of "Hierarchical"
In many places, I spelled it "Hierarchal"

### PR DESCRIPTION
**Pull request by passiweinberger**
The Synonyms were confusing...

fixes #178.

### CODE REVIEW

**Comment by rhyolight** [comment]
Some more places:

```
_includes/content/community-content.md
9:## [Hierarchal Temporal Memory - Persian]({{ site.baseurl }}/resources/community-content/Hierarchical%20Temporal%20Memory%20-%20Persian.pdf)

_includes/content/htm-white-paper.md
3:Hierarchal Temporal Memory is fully detailed in the following white paper. The document is available in several languages, thanks to the generosity of the translators listed below (The accuracy of these translations has not been verified).

_includes/content/htm.md
2:# Hierarchal Temporal Memory (HTM)
12:In humans, these capabilities are largely performed by the neocortex. Hierarchal

_includes/content/landing.md
18:At the heart of NuPIC is Hierarchal Temporal Memory, or HTM. HTM has a deep biological mapping which will be interesting to neuroscientists. From an algorithmic point of view there are three principle properties.
29:Are you interested in learning more about the brain-inspired [Hierarchal Temporal Memory](htm.html) Numenta has developed over the past several years? Or maybe you just want to check out our open source software, [NuPIC](nupic.html). You might even want to better understand [what Numenta is all about](about.html). Are you ready to interact with our [community]({{ site.baseurl }}/community.html)? Then join our [mailing list]({{ site.baseurl }}/lists) and ask us some questions!

_includes/old/nav.html
4:        <li><a href="{{ site.baseurl }}/htm.html">Hierarchal Temporal Memory</a></li>

blog/_posts/2013-11-11-cla-quiz-office-hour.md
8:Tomorrow at 4PM Pacific, we're holding an [Office Hour](https://plus.google.com/b/100642636108337517466/events/crmrf6k58s77hlgk4v30bll8hp8) for anyone interested to join in and talk about [Hierarchal Temporal Memory]({{ site.baseurl/htm-white-paper.html }}), as implemented by Numenta within [NuPIC]({{ site.baseurl/nupic.html }}). Jeff Hawkins and Numenta VP of Engineering Subutai Ahmad will be at this event to go through the _CLA Quiz_, a serious of challenging questions about how NuPIC algorithms work. These questions were originally created for new employees and interns to research in order to better understand the CLA. Tomorrow, we're going to be asking you!
```

**Comment by passiweinberger** [comment]
In work :)

**Comment by rhyolight** [comment]
blog_highfive

**Comment by passiweinberger** [comment]
All ? :) Think so :+1:

**Pull request merged**
