### PR TITLE
Add line to indicate the CL form will take a second to load.

### PR DESCRIPTION
**Pull request by scottpurdy**
@brev @rhyolight - I think it would be better to have a loading indicator that is replaced when the form loads but didn't see an easy way to do that so this is my poor man's version. Open to suggestions.

### CODE REVIEW

**Comment by rhyolight** [comment]
Yeah, it's Flash :confounded: so there's no easy way to get a loaded event. But this is a fine change.

**Comment by rhyolight** [comment]
@scottpurdy can you add the same line to http://numenta.org/licenses/trial/ as well?

**Comment by scottpurdy** [comment]
@rhyolight - done

**Comment by rhyolight** [comment]
:+1: thanks

**Pull request merged**
