### PR TITLE
New Numenta.org Website Going Live

### PR DESCRIPTION
**Pull request by brev**
New Numenta.org Website slowly merging into production and Going Live

cc @rhyolight @jcasner

### CODE REVIEW

**Comment by brev** [comment]
also cc @cogmission

**Comment by brev** [comment]
looks good to go. checking personal staging site one more time first.

**Comment by brev** [comment]
merging now.

**Comment by brev** [comment]
Live!

**Comment by cogmission** [comment]
You are made of awesomeness Brev!

Congratulations! It looks great!



On Fri, Jul 10, 2015 at 2:46 PM, Brev Patterson <notifications@github.com>
wrote:

> Live!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/numenta.org/pull/215#issuecomment-120505400>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by brev** [comment]
thank you @cogmission! :)  very much appreciated.

**Pull request merged**
