### PR TITLE
Blog and docs for HTM.Java NAPI.

### PR DESCRIPTION
**Pull request by rhyolight**
@cogmission

### CODE REVIEW

**Comment by cogmission** [comment]
@rhyolight  @brev  I don't understand. Does this go up on Numenta's site upon merging? And how would I update these docs in the future?

**Comment by rhyolight** [comment]
@cogmission Yes! This is the source code for numenta.org. Upon merge, numenta.org will be automatically updated. 

If you want to update your HTM.Java docs in the future, just replace the docs in https://github.com/numenta/numenta.org/tree/gh-pages/docs/htm.java with a new version.

**Comment by cogmission** [comment]
@rhyolight Very cool! ok...

On Mon, Jun 8, 2015 at 3:03 PM, Matthew Taylor <notifications@github.com>
wrote:

> @cogmission <https://github.com/cogmission> Yes! This is the source code
> for numenta.org. Upon merge, numenta.org will be automatically updated.
>
> If you want to update your HTM.Java docs in the future, just replace the
> docs in https://github.com/numenta/numenta.org/tree/gh-pages/docs/htm.java
> with a new version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/numenta.org/pull/211#issuecomment-110121867>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by rhyolight** [comment]
@cogmission please review staging site at http://rhyolight.github.io/numenta.org/blog/2015/06/08/htm-java-receives-new-network-api.html and let me know if anything else is wrong.

**Comment by cogmission** [comment]
@rhyolight Looks good! Let's roll camera! :)

On Mon, Jun 8, 2015 at 3:05 PM, Matthew Taylor <notifications@github.com>
wrote:

> @cogmission <https://github.com/cogmission> please review staging site at
> http://rhyolight.github.io/numenta.org/blog/2015/06/08/htm-java-receives-new-network-api.html
> and let me know if anything else is wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/numenta.org/pull/211#issuecomment-110122166>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Pull request merged**
